services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: NetUsers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jmh990

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [database]
    restart: always
    ports:
      - "5001:5001"
    expose:
      - 5001
    volumes:
      - ./:/app/